const fiveLetterWordsOld = [
    "apple",
    "brick",
    "chair",
    "dance",
    "eagle",
    "flute",
    "grape",
    "honey",
    "index",
    "jolly",
    "knife",
    "lemon",
    "mouse",
    "noble",
    "ocean",
    "paint",
    "queen",
    "river",
    "stone",
    "table",
    "under",
    "vivid",
    "whale",
    "xenon",
    "youth",
    "zebra",
    "pform",
    "rpgju",
    "jbcvm",
    "bntrl",
    "tjiov",
    "htceg",
    "wowrm",
    "habyf",
    "ejxhh",
    "vfawa",
    "ypczp",
    "sckrd",
    "kqebw",
    "jwewi",
    "urrnp",
    "fswnd",
    "sutim",
    "gtuig",
    "ebzet",
    "sruit",
    "drjjc",
    "kklhd",
    "qfcto",
    "vjguj",
    "dvwdo",
    "wjcnw",
    "dqsne",
    "ethax",
    "lavph",
    "hpckq",
    "aklan",
    "jmocw",
    "pvzvq",
    "sugpz",
    "lxreq",
    "sadqe",
    "wycmk",
    "wnddr",
    "ugxve",
    "prfvb",
    "ytetz",
    "meniy",
    "eymic",
    "xttxk",
    "lorad",
    "tfgaz",
    "cezqq",
    "rpsrj",
    "dgfeq",
    "cnhgs",
    "qymzh",
    "pyofu",
    "aflfg",
    "ldbmz",
    "nilye",
    "cbuup",
    "xnnxn",
    "ehisl",
    "vnfnj",
    "hoeof",
    "hgiiw",
    "lkong",
    "uewux",
    "ldnnz",
    "tsaax",
    "bdkzi",
    "flaxd",
    "xsnbf",
    "nzzzb",
    "lraya",
    "mjykw",
    "ymohx",
    "mmucu",
    "watph",
    "shvqo",
    "sfajg",
    "jvoep",
    "lswsj",
    "ymeha",
    "kxded",
    "qwazu",
    "mgwaa",
    "iadjs",
    "kxqnh",
    "afcoo",
    "gwdzx",
    "iatye",
    "obbpo",
    "zvlcc",
    "gtnxz",
    "pxrbc",
    "nrznd",
    "hhqkm",
    "noxrh",
    "ekffe",
    "lhoye",
    "kpdud",
    "yuzeb",
    "bwjnc",
    "robgm",
    "efqto",
    "bnyxn",
    "mgvlr",
    "wyrxw",
    "wpwyh",
    "glusm",
    "gldba",
    "mgcjs",
    "jowkj",
    "xoimq",
    "youct",
    "wyqlj",
    "zoedx",
    "fyakq",
    "rcdrf",
    "wisto",
    "wuoid",
    "owezu",
    "wxukq",
    "iiwcg",
    "ghwzu",
    "lqwlw",
    "hszdz",
    "ljkje",
    "meirj",
    "uxima",
    "appsy",
    "nlzcz",
    "devtu",
    "tkkyx",
    "lesix",
    "jshch",
    "eqelh",
    "wrueg",
    "euqey",
    "rzvxz",
    "lhagt",
    "dnqod",
    "jqiba",
    "vqyds",
    "afyhc",
    "lceml",
    "nakox",
    "zkmgi",
    "vxxzg",
    "wktie",
    "yzbth",
    "zkiia",
    "lbxuo",
    "ncoqn",
    "bprgh",
    "nsvtw",
    "bxqac",
    "ihhog",
    "jomyv",
    "xpvoi",
    "gyxno",
    "nbbhc",
    "ctfid",
    "sjsjt",
    "cmlkj",
    "kbeaf",
    "ucfgn",
    "uebju",
    "lawna",
    "cygvr",
    "ktrku",
    "ylgwb",
    "pnbhg",
    "oklei",
    "gbsun",
    "vgrtr",
    "rsdff",
    "dcjjp",
    "seosb",
    "utrjp",
    "kfmey",
    "mujox",
    "pmlbt",
    "qwbec",
    "lpfiu",
    "bvaqu",
    "qfsjo",
    "zegvk",
    "rgkde",
    "mwslm",
    "lnazh",
    "thzti",
    "irmwg",
    "wtzuz",
    "xdlah",
    "kebrc",
    "ymqmw",
    "mqvdf",
    "zeygx",
    "brtty",
    "drjjl",
    "xmwrh",
    "zkgjc",
    "twwbs",
    "hezax",
    "wbccq",
    "wdmcp",
    "nushl",
    "nfowb",
    "ophqx",
    "mlswk",
    "bxtqc",
    "grnev",
    "fclik",
    "oosff",
    "zanne",
    "sokwu",
    "bxweg",
    "cltxc",
    "tspqx",
    "iwtzo",
    "fjftw",
    "ngjzu",
    "sansn",
    "sxeyk",
    "srfdz",
    "jelal",
    "mwigw",
    "vdrqs",
    "rhcyg",
    "ivpcu",
    "zsthd",
    "fijwo",
    "rdwzt",
    "iuwqd",
    "nqexo",
    "arwgk",
    "xitcs",
    "qksui",
    "uunpu",
    "rcjkd",
    "wdecm",
    "ghyqd",
    "netaj",
    "uucce",
    "vjrht",
    "hniem",
    "iyjin",
    "coxeo",
    "rjhwd",
    "jfsip",
    "srxvt",
    "ypfdc",
    "uvkic",
    "sraby",
    "lbngi",
    "xllgn",
    "aeldg",
    "iazzl",
    "pogjz",
    "wryuu",
    "ygqnd",
    "iybmf",
    "xvphz",
    "hbxpw",
    "vjmvf",
    "msuvd",
    "cphzr",
    "kwqoi",
    "enoas",
    "euyhd",
    "nvmkx",
    "ruhqq",
    "epgsz",
    "fyhax",
    "ecfnt",
    "bkqtf",
    "gnznj",
    "unvxu",
    "tbzcf",
    "dplpc",
    "snvep",
    "lxych",
    "eqzbs",
    "lwqlq",
    "fforf",
    "bzcpe",
    "dyvcf",
    "tmmzh",
    "wwwaz",
    "qeyxh",
    "ygqls",
    "vfsov",
    "tzioi",
    "shckx",
    "urpqy",
    "npljx",
    "kxtsc",
    "zveka",
    "hdorb",
    "iqbio",
    "etlpf",
    "fowne",
    "baclm",
    "klbcl",
    "zxrxb",
    "xktac",
    "owjwt",
    "rlxaa",
    "oeahm",
    "wjrqc",
    "ihjhy",
    "hvqfu",
    "rwrkj",
    "hydvd",
    "udjly",
    "sovpe",
    "snrhl",
    "uoybq",
    "bcgnj",
    "rhxyj",
    "otklu",
    "vopjt",
    "ziskc",
    "cwung",
    "cwrad",
    "pzbkx",
    "coobd",
    "uqske",
    "nirmu",
    "ucfem",
    "nsjre",
    "petua",
    "rjzhu",
    "qwsut",
    "vupqd",
    "mqgld",
    "cwjkm",
    "tbhzq",
    "fguii",
    "csrth",
    "eettt",
    "fviqo",
    "ipzjv",
    "wyofm",
    "cvgbi",
    "mqvwz",
    "rwmoc",
    "lmsxl",
    "zzyrh",
    "oquex",
    "ypcet",
    "dffxb",
    "gledh",
    "gnywf",
    "hdkni",
    "oysoq",
    "tcgab",
    "zrttg",
    "pmwyx",
    "sqkaz",
    "rovvk",
    "kehep",
    "bvsmc",
    "byuty",
    "wztfn",
    "pmjku",
    "lchbr",
    "dilso",
    "xtktn",
    "babci",
    "myomv",
    "mcieu",
    "odhux",
    "uehqh",
    "zahvk",
    "jyibh",
    "vxfft",
    "tkigw",
    "unpjm",
    "jlbhz",
    "wqjrh",
    "tefng",
    "qonin",
    "vxvfb",
    "mfnee",
    "ijwpb",
    "nkrak",
    "wlvvy",
    "agsfj",
    "mcnyg",
    "elmyj",
    "xzdth",
    "susij",
    "hywkm",
    "euvcv",
    "yjrny",
    "jqndr",
    "utfhj",
    "zzixj",
    "fouwn",
    "rrjce",
    "ztkmm",
    "abupg",
    "fyzof",
    "xqxsi",
    "dmoyx",
    "wdkbv",
    "lukkl",
    "sanss",
    "wmoln",
    "udxjn",
    "wjeib",
    "hirrh",
    "pnkfi",
    "oyufc",
    "bgjtz",
    "yfeag",
    "rwavf",
    "tvtfv",
    "kuxie",
    "jqdkr",
    "iwodo",
    "llabk",
    "rshaz",
    "alqid",
    "evqxs",
    "engmg",
    "dklnp",
    "mipjp",
    "khydf",
    "xhhjr",
    "efxhn",
    "npgnk",
    "txvzl",
    "xfgaq",
    "tcwfk",
    "yhdgb",
    "wmiso",
    "eyjqv",
    "agfdj",
    "qrlpr",
    "rdmcz",
    "hjidf",
    "frpfg",
    "iifhk",
    "desiq",
    "iuxkp",
    "hvqps",
    "zmwpc",
    "cxwbg",
    "feszc",
    "tdutm",
    "ceygz",
    "jjyug",
    "iapex",
    "pmlmc",
    "ynexv",
    "wbfqj",
    "rgjho",
    "sfabz",
    "bpjok",
    "fuyjb",
    "nuokl",
    "imrbj",
    "onzcw",
    "calsq",
    "xywcg",
    "juhsh",
    "exhqg",
    "zjndn",
    "bxqgq",
    "vxlcp",
    "cgpke",
    "sdvdg",
    "kptke",
    "yuktx",
    "mgqwl",
    "vbihk",
    "spjdc",
    "tdyek",
    "ceajm",
    "gryae",
    "onrze",
    "dmhhc",
    "khbys",
    "kyoec",
    "ilcat",
    "gksqg",
    "brwpr",
    "emzgk",
    "zmoqh",
    "bspfo",
    "ktudb",
    "qhqsi",
    "fahtl",
    "srpgg",
    "phvki",
    "jymiy",
    "ejflo",
    "ahwes",
    "ybvlf",
    "xminq",
    "drjhm",
    "ibyby",
    "pemwj",
    "usras",
    "uzkwn",
    "ewlrf",
    "ufzax",
    "efkyi",
    "acabv",
    "ozxmc",
    "bzkff",
    "qjswx",
    "lddwu",
    "mguty",
    "btjkt",
    "csngp",
    "myilb",
    "excbu",
    "skojm",
    "unbrv",
    "vnofy",
    "ikkgz",
    "uclag",
    "kwydz",
    "ptkuj",
    "csxah",
    "cmxao",
    "dggaz",
    "akqev",
    "qnrgo",
    "nzemm",
    "gsjwb",
    "suxrm",
    "pjzbz",
    "pauto",
    "besbj",
    "jbrvg",
    "wuyya",
    "otfgv",
    "ttayg",
    "xyrmx",
    "hhlzy",
    "bafxp",
    "qboew",
    "xvdvn",
    "ghhwg",
    "rgxmj",
    "wdcdg",
    "uzksk",
    "elyrz",
    "jzxqr",
    "zfkie",
    "xzdmx",
    "gziid",
    "gfxzz",
    "prnqm",
    "yztsl",
    "gkbdq",
    "upooi",
    "dwiql",
    "daxpe",
    "qhfua",
    "yvgor",
    "miqsq",
    "bkktb",
    "fmvfp",
    "utzmu",
    "ebxci",
    "unkvc",
    "umqla",
    "mjhsa",
    "rrqyg",
    "awhvp",
    "czmyv",
    "ancvx",
    "kyads",
    "rgcoy",
    "esfkg",
    "tpcmo",
    "vngnx",
    "ejhtv",
    "wnuaz",
    "vyvbv",
    "ctrrd",
    "zwuwa",
    "iplya",
    "sitai",
    "rmrrp",
    "iekaq",
    "zkief",
    "kxjpt",
    "lgpsa",
    "jicxd",
    "fgzds",
    "yagfj",
    "sptmj",
    "advlm",
    "wjzai",
    "kyljl",
    "gmtje",
    "trsym",
    "gbmbh",
    "wjysc",
    "nxwor",
    "rzrms",
    "fliar",
    "hshqu",
    "vfrzi",
    "jbmzx",
    "xgmbv",
    "alxth",
    "cpdit",
    "amdtk",
    "xevsi",
    "ybudk",
    "hgrdu",
    "buphp",
    "isbrs",
    "asybz",
    "yxnpa",
    "ubkvt",
    "mucye",
    "ltijx",
    "azjsc",
    "eqkkr",
    "hvwoz",
    "qbamf",
    "uxmxo",
    "fbtha",
    "hwltj",
    "miupg",
    "zcmsn",
    "hxqrn",
    "nzsdl",
    "duejy",
    "fdaqs",
    "mzctn",
    "eujad",
    "octgx",
    "riwje",
    "bwnfr",
    "xtxec",
    "jccgh",
    "hkhor",
    "tmemg",
    "opunw",
    "afjkm",
    "mohpr",
    "lurev",
    "pmpgh",
    "iaxvj",
    "tcjcz",
    "wfqfj",
    "wyqun",
    "tfnyd",
    "zuosx",
    "htavs",
    "lywbs",
    "ywsss",
    "vbpky",
    "fbalv",
    "agefw",
    "dpmpt",
    "ulmxp",
    "pbxdv",
    "rbcig",
    "rzmpn",
    "lxzzj",
    "esvhq",
    "dazia",
    "pssuj",
    "sfjol",
    "nxwnx",
    "yuyka",
    "tqvgc",
    "dlxrw",
    "uisdv",
    "obmrr",
    "feyxv",
    "cprla",
    "lfuif",
    "anyco",
    "mavdo",
    "mkrwr",
    "opvze",
    "mqzib",
    "rdlag",
    "cnmyq",
    "yfbsg",
    "muntj",
    "hvtuj",
    "rvydw",
    "iythe",
    "hvvfy",
    "ndoto",
    "ernyx",
    "owuvl",
    "tniit",
    "umatz",
    "mumis",
    "wepra",
    "geieq",
    "rgdtq",
    "mhqrm",
    "knbsr",
    "mxfla",
    "rfdjd",
    "fsmab",
    "ujdsy",
    "qydzu",
    "jkscv",
    "utygt",
    "bbwcq",
    "unxih",
    "ydbdn",
    "yxjbw",
    "deefj",
    "saulb",
    "rsoae",
    "yekcp",
    "fwaqd",
    "itgag",
    "vcvkf",
    "gymso",
    "vaamp",
    "fntji",
    "bhaol",
    "fxfgk",
    "drwyi",
    "qliek",
    "qpqpg",
    "hupnh",
    "dckzi",
    "xeyhj",
    "fpwnv",
    "guowf",
    "oykiu",
    "pujcc",
    "kqjkk",
    "agzbe",
    "kgalx",
    "cpqot",
    "qsdsj",
    "ihhjn",
    "iwsto",
    "rxyqj",
    "hsayb",
    "bfuuw",
    "epiwl",
    "gjkrv",
    "euvqu",
    "cnetc",
    "osbxv",
    "wlbwo",
    "hyldg",
    "rnrwg",
    "tdvzr",
    "tbqpo",
    "lldeu",
    "pqpil",
    "mylbd",
    "ivpgt",
    "ygrbf",
    "rkkde",
    "jdfbv",
    "bgajj",
    "xqhbb",
    "uadgs",
    "rmyoi",
    "atulk",
    "kghri",
    "tbaue",
    "jmmqd",
    "sfavk",
    "tafbc",
    "irwww",
    "ggtnr",
    "rvsue",
    "rczhb",
    "fmisz",
    "ocyiv",
    "fadaq",
    "saruf",
    "sngqi",
    "sxwih",
    "bspwn",
    "gimjb",
    "nfknp",
    "oncry",
    "wdbof",
    "qyiri",
    "bqykr",
    "lmljr",
    "vsqaf",
    "jsseq",
    "lpgpy",
    "cmtvv",
    "togur",
    "boxfl",
    "mcgsi",
    "vmxpo",
    "faufb",
    "jumnf",
    "riuvk",
    "ioggm",
    "yhrki",
    "ikxiz",
    "zwdkk",
    "xjnjq",
    "tekld",
    "cktgr",
    "miwwi",
    "dphvb",
    "qcydm",
    "ainqm",
    "fpndv",
    "dozha",
    "fyedh",
    "lrgfe",
    "pgsjn",
    "ommrp",
    "sqiqg",
    "ujunp",
    "wkbar",
    "lanem",
    "ksfgg",
    "sdjed",
    "yepni",
    "ziukf",
    "tqvtc",
    "gcokh",
    "dlkds",
    "ragnu",
    "bbbhn",
    "vibfv",
    "qlsjx",
    "hzweg",
    "uthpk",
    "cnpfb",
    "lakqn",
    "oajgd",
    "benfc",
    "ivpry",
    "wsklj",
    "nvcns",
    "xrqpu",
    "fusql",
    "zpyzs",
    "vjqyg",
    "ypidm",
    "qysmp",
    "xdarl",
    "bsrzz",
    "pbcdd",
    "jnzti",
    "faufg",
    "havqz",
    "wbfgf",
    "bneie",
    "jjyxr",
    "ejuaq",
    "oejvm",
    "homcj",
    "dzooo",
    "mwhjr",
    "ysaey",
    "nuctw",
    "gjkis",
    "hskzg",
    "jvmfh",
    "kamhw",
    "jmrvj",
    "zfosf",
    "uvulr",
    "edtwk",
    "wyxzf",
    "lnxht",
    "hyvdt",
    "lppab",
    "syqsl",
    "sgmzt",
    "swkdu",
    "gylvy",
    "thzlx",
    "wsioh",
    "zjyxb",
    "iuhfo",
    "gblqr",
    "fmvad",
    "jzkut",
    "lifza",
    "eyzdv",
    "isngr",
    "qghke",
    "dratw",
    "aalsq",
    "aghpw",
    "qrdyu",
    "etfkf",
    "kvguh",
    "xfdte",
    "orotz",
    "loaiw",
    "gksne",
    "nvyam",
    "sduvm",
    "dpypq",
    "zasnq",
    "vfgvo",
    "vbvdg",
    "evpnc",
    "tdlwr",
    "zfpfd",
    "nlvgm",
    "krhuu",
    "gljwx",
    "yzjww",
    "rzfkv",
    "zmqtz",
    "gjkfv",
    "oyvnh",
    "zochp",
    "jokou",
    "kthzv",
    "iyyff",
    "jorno",
    "wycjr",
    "rrhpn",
    "rgxvz",
    "atkot",
    "lqzmq",
    "cvxmg",
    "frchm",
    "dpmyv",
    "caxlr",
    "trsbi",
    "iiujz",
    "kdxzl",
    "gfcia",
    "iqemz",
    "zmggc",
    "gfbly",
    "oqueh",
    "hwjlm",
    "whkxv",
    "hxxmv",
    "urufk",
    "swhuc",
    "lrlrw",
    "oudbx",
    "hqnax",
    "rbcnp",
    "jqddj",
    "xmcjd",
    "yhbuo",
    "idloy",
    "skutj",
    "mrfwq",
    "aqidr",
    "kmaog",
    "bnmjp",
    "rhxgd",
    "rpvfn",
    "qfurk",
    "prudo",
    "moqpw",
    "ehcfz",
    "rsebn",
    "ngdix",
    "tzgcl",
    "ioabm",
    "kwbbr",
    "icgho",
    "dwglc",
    "auukj",
];

//Test Words
const fiveLetterWords = [
    "apple", "acres", "eagle", "slice",
    "axles", "attic", "stick", "click",
    "trick", "track", "knock", "knick",
    "slash", "super", "happy", "rally",
    "power", "poach", "roast", "heart",
    "ether", "earth", "ropes", "hopes"
]
// 168 unique letters
// 12*12 + 8*3 (12 inner spots on each face (12 faces on big cube) + 8 corners with 3 spots)
// 5 letter words -> 96 unique letters
// 3 letter words -> 72 unique letters

const threeLetterWords = [
    "cat", "dog", "bat", "rat", "sun", "run", "fun", "box", "fix", "mix",
    "max", "pop", "zip", "lip", "tip", "top", "bit", "fit", "hit", "kit",
    "net", "pet", "jet", "met", "let", "bet", "set", "get", "sit", "pit",
    "wit", "lit", "mat", "pat", "hat", "vat", "sat", "fat", "fan", "man",
    "pan", "tan", "ran", "ban", "can", "dam", "ham", "jam", "cab", "lab",
    "tab", "fab", "nab", "gap", "sap", "lap", "map", "nap", "tap", "cap",
    "rap", "zap", "yap", "sip", "dip", "hip", "lip", "tip", "nip", "rip",
    "pip", "cup", "pup", "sup", "hut", "cut", "nut", "but", "put", "gut",
    "tot", "bot", "cot", "dot", "got", "lot", "pot", "rot", "sot", "not",
    "hot", "bid", "did", "rid", "lid", "mid", "kid", "pod", "nod", "rod",
    "cod", "sod", "god", "fog", "hog", "jog", "log", "bog", "cog", "tog",
    "tag", "wag", "bag", "rag", "lag", "nag", "hag", "big", "dig", "pig",
    "wig", "fig"
];

function getRandomWords(array, numWords, wordException = '') {
    // Filter out the wordException
    const filteredArray = array.filter(word => word !== wordException);
    // Fisher-Yates shuffle algorithm
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array.slice(0, numWords);
}

const cubeThreeLetterWords = [...getRandomWords(threeLetterWords, 24)];

console.log(cubeThreeLetterWords);

function createCubeMap(wordMap) {
    const cubeMap = {};

    function addLetterToCubeMap(x, y, z, letter, cbMap, plane) {
        const key = `${x},${y},${z}`;
        if (!cbMap[key]) {
            cbMap[key] = {};
        }

        cbMap[key][plane] = letter;
    }
    function processPlane(plane, xModifier, yModifier, zModifier) {
        let tmpCubeMap = {};
        const words = wordMap[plane];
        // For 3 letter words 
        const opp = opposites[plane] || Object.keys(opposites).find(key => opposites[key] === plane);
        
        let xInit = xModifier.initial;
        let yInit = yModifier.initial;
        let flipper = 1;
        words.forEach((word, wordIndex) => {
            const three_letter_word = getThreeLetterWord();
            if (wordIndex === 2) {
                xModifier.initial = -1 * xModifier.initial;
                flipper = -1;
            } else {
                xModifier.initial = xInit;
                flipper = 1;
            }
            if (wordIndex === 3) {
                yModifier.initial = -1 * yModifier.initial;
                flipper = -1;
            } else {
                yModifier.initial = yInit;
                flipper = 1;
            }
            xModifier.curr = xModifier.initial;
            yModifier.curr = yModifier.initial;
            for (let i = 0; i < word.length; i++) {
                if (wordIndex == 0 || wordIndex == 3) {
                    xModifier.curr = xModifier.initial + i * xModifier.increment;
                } else {
                    yModifier.curr = yModifier.initial + i * yModifier.increment;
                }
                // Determine which modifier has the coord "x"
                const coordMap = {
                    [xModifier.coord]: xModifier.curr,
                    [yModifier.coord]: yModifier.curr,
                    [zModifier.coord]: zModifier.curr
                };

                let key2 = `${coordMap.x},${coordMap.y},${coordMap.z}`;

                if (tmpCubeMap[key2]) {
                    if (tmpCubeMap[key2][plane] !== word[i]) throw new Error("letters don't match");
                    continue;
                }

                addLetterToCubeMap(coordMap.x, coordMap.y, coordMap.z, word[i], tmpCubeMap, plane);
                addLetterToCubeMap(coordMap.x, coordMap.y, coordMap.z, word[i], cubeMap, plane);
                
                if(i > 0 && i < word.length - 1){
                    addLetterToCubeMap(coordMap.x, coordMap.y, coordMap.z, three_letter_word[three_letter_word.length - (i)], cubeMap, opp);
                }

            }
        });
        tmpCubeMap = {};
    }

    class CoordModifier {
        constructor(initial, increment, coord) {
            this.initial = initial;
            this.increment = increment;
            this.coord = coord; //"x", "y", "z"
            this.curr = initial;
        }
    }

    // Process the "top" plane (0, 0, 1)
    let xMod = new CoordModifier(-1, 0.5, "x");
    let yMod = new CoordModifier(-1, 0.5, "z");
    let zMod = new CoordModifier(1, 0, "y");
    processPlane('top', xMod, yMod, zMod);

    // Process the "bottom" plane (0, 0, -1)
    xMod = new CoordModifier(-1, 0.5, "x");
    yMod = new CoordModifier(1, -0.5, "z");
    zMod = new CoordModifier(-1, 0, "y");
    processPlane('bottom', xMod, yMod, zMod);

    // Process the "left" plane (-1, 0, 0)
    xMod = new CoordModifier(-1, 0.5, "z");
    yMod = new CoordModifier(1, -0.5, "y");
    zMod = new CoordModifier(-1, 0, "x");
    processPlane('left', xMod, yMod, zMod);

    // Process the "right" plane (1, 0, 0)
    xMod = new CoordModifier(1, -0.5, "z");
    yMod = new CoordModifier(1, -0.5, "y");
    zMod = new CoordModifier(1, 0, "x");
    processPlane('right', xMod, yMod, zMod);

    // Process the "front" plane (0, -1, 0)
    xMod = new CoordModifier(-1, 0.5, "x");
    yMod = new CoordModifier(1, -0.5, "y");
    zMod = new CoordModifier(1, 0, "z");
    processPlane('front', xMod, yMod, zMod);

    //`Process the "back" plane (0, 1, 0)
    xMod = new CoordModifier(1, -0.5, "x");
    yMod = new CoordModifier(1, -0.5, "y");
    zMod = new CoordModifier(-1, 0, "z");
    processPlane('back', xMod, yMod, zMod);

    return cubeMap;
}

// Example usage
const wordMap = {
    "top": ["apple", "acres", "eagle", "slice"],
    "bottom": ["axles", "attic", "stick", "click"],
    "left": ["trick", "track", "knock", "knick"],
    "right": ["slash", "super", "happy", "rally"],
    "front": ["power", "poach", "roast", "heart"],
    "back": ["ether", "earth", "ropes", "hopes"]
};

const opposites = {
    "top": "bottom",
    "left": "right",
    "front": "back"
}

const cubeMap = createCubeMap(wordMap);
console.log(cubeMap);
console.log(Object.keys(cubeMap).length);

// should be 61 total cubes


function findRandomWordStartingWith(words, letter, existingWords) {
    const matchingWords = words.filter(word => word[0].toLowerCase() === letter.toLowerCase());
    if (matchingWords.length === 0) return null;
    const randomIndex = Math.floor(Math.random() * matchingWords.length);
    return matchingWords[randomIndex];
}

function findRandomWordEndingWith(words, letter, existingWords) {
    const matchingWords = words.filter(word => word[word.length - 1].toLowerCase() === letter.toLowerCase());
    if (matchingWords.length === 0) return null;
    const randomIndex = Math.floor(Math.random() * matchingWords.length);
    return matchingWords[randomIndex];
}

function findRandomWordStartingWithAndEndingWith(words, startletter, endletter, existingWords) {
    const matchingWords = words.filter(word => word[0].toLowerCase() === startletter.toLowerCase() && word[word.length - 1].toLowerCase() === endletter.toLowerCase());
    if (matchingWords.length === 0) return null;
    const randomIndex = Math.floor(Math.random() * matchingWords.length);
    return matchingWords[randomIndex];
}



function getThreeLetterWord(){
    const word = cubeThreeLetterWords[Math.floor(Math.random() * cubeThreeLetterWords.length)];
    cubeThreeLetterWords.splice(cubeThreeLetterWords.indexOf(word), 1);
    return word;
} 

export default function getWordsForCube() {
    // need to retrieve 24 3 letter words
    let wordsList = [];
    // each face has 4 5 letter words -> so 24 5 letter words BUT each face needs to start and stop with the same letter
    wordsList.push(...getRandomWords(threeLetterWords, 24));
    /*for(var i = 0; i < 6; i++){
        const word1 = getRandomWords(fiveLetterWords, 1);
        wordsList.push(word1);
        const word2 = findRandomWordStartingWith(fiveLetterWords, word1[0], wordsList);
        wordsList.push(word2);
        const word3 = findRandomWordStartingWith(fiveLetterWords, word1[word1.length-1], wordsList);
        wordsList.push(word3);
        const word4 = findRandomWordStartingWithAndEndingWith(fiveLetterWords, word2[word2.length-1], word3[word3.length-1], wordsList);
        wordsList.push(word4);
        if word1 == null || word2 == null || word3 == null || word4 == null {
            console.log("Error: Could not find words to match criteria");
            return null;
        }
    }*/
    //const circularLinkedWords = getCircularLinkedWords(fiveLetterWords, 4, 6);
    //console.log(circularLinkedWords);
    wordsList.push(...fiveLetterWords);
    return cubeMap;
}

// Word order on cubes is right, left, top, bottom, front, back
// To keep things consistent, we will use the same order for the words

